### ISSUE TITLE
Add support for aliases in JSON API

### ISSUE THREAD

**Issue by alexander-schranz** [RedisJSON/RedisJSON#1197]
I'm using RediSearch with RedisJson in my Search Engine Abstraction Layer for PHP: https://github.com/schranz-search/schranz-search.

I'm currently implementing Zero Downtime Reindexing via Index aliases. The big problem is that I can create Aliases for Indexes but as I require to us RedisJson, I'm currently failing as I can not also not use the aliases name for my `JSON.SET` calls.

So it would be great to have `JSON.ALIASADD`, `JSON.ALIASDEL`, `JSON.ALIASUPDATE` similar to the RediSearch module.

**Comment by LiorKogan** [comment]
I'm not sure I understand what you are missing.
RedisJSON doesn't have an index concept. What would be the arguments of such commands?

**Comment by alexander-schranz** [comment]
Aliases are a common concept where I can access something via another defined way.

```
JSON.ALIASADD myjson myjson_20230311

JSON.SET myjson # writes to myjson_20230311

JSON.GET myjson # read from myjson_20230311
```

**Comment by LiorKogan** [comment]
So you want to alias a Redis key. I believe it should be implemented as a Redis command. The key type (JSON / hash / list) shouldn't matter and the implementation should be specific for JSON.

I suggest to close this issue and open a similar issue in Redis GitHub repository.

For RediSearch - aliasing is for an index, not for a key. That's why it was implemented in the module level.

**Comment by alexander-schranz** [comment]
@LiorKogan make sense. Thank you for your fast response here.
