### ISSUE TITLE
Slicing operator doesn't work?

### ISSUE THREAD

**Issue by leppaott** [RedisJSON/RedisJSON#1227]
Cache:
```
{"6735211916691083016":{"timestamp":300},
"6735211916691083017":{"timestamp":1111},
"6735211916691083018":{"timestamp":1999}}
```

```
"$.[?(@.timestamp>1)][0:2]"
```

Why doesn't this array slicing return any results, just an empty list? Without the `[0:2]` part it returns all of the objects.
Is this because it'd only work for an actual array field like `timestamps: [1,2,3,4]`.

**Comment by LiorKogan** [comment]
Hi @leppaott 

That's not how JSONPath works.

Each filter step is not executed on all matches of the previous step, but on each match of the previous step separately. JSONPath does not have a `grouping` step.

For the path expression `$.[?(@.timestamp>1)][0:2]`, the part `[0:2]` is executed on each of the matches of `$.[?(@.timestamp>1)]`, and since none of the matches is an array (they are all single-element objects) - the result is empty.

Try the following path expression: `$.[?(@.timestamp>1)].timestamp` - the result is `"[300,1111,1999]"` - which is an array of all matches, but JSONPath does not provide you with a way to filter this array.

**Comment by leppaott** [comment]
Thanks @LiorKogan
