### ISSUE TITLE
Complete support for GET

### ISSUE THREAD

**Issue by gkorland** [RedisJSON/RedisJSON#145]
```
JSON.GET <key>
         [INDENT indentation-string]
         [NEWLINE line-break-string]
         [SPACE space-string]
         [NOESCAPE]
         [path ...]
```

https://oss.redislabs.com/rejson/commands/#jsonget

**Comment by yoav-steinberg** [comment]
Some questions, @itamarhaber I'd like your feedback
* Why was the `SPACE` option originally created? I mean I can understand if you want to compact the output and eliminate the spaces but changing them to a non-space char? Doesn't make sense. It could have just been a boolean option.
* Same for `NEWLINE`, could have just been a boolean. Or if we want to support CRLF then just have CRLF option and not a newline char specifier.
* For `INDENT`, it makes sense to have either \t or number of spaces (with a default of 0 meaning no spaces). Again specifying a char doesn't make sense here.
* For the new `FORMAT` options we could just go with a `BSON` boolean option unless we plan to add additional formats in the future (msgpack, protobuf...).
I think since we're already making changes it might be worth considering breaking compatibility here (as mentioned in docs regarding changing the `NOESCAPE` behavior in the future).

**Comment by itamarhaber** [comment]
Hello @yoav-steinberg - it has been a while since this was done but:

> Why was the SPACE option originally created?

It is intended to be a way to replace the white space, like in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

> Same for NEWLINE

CR, CRLF, space or any other white space

> For INDENT

It isn't a char, it is a string so if you want two \t you can do it. I agree it isn't the most useful feature.

I'm all for breaking compatibility :P

**Comment by yoav-steinberg** [comment]
Ok, for now I'm going to keep all as is except `NOESCAPE`. I see not all options have a unit test, so I'll try to fix that.

Re `NOESCAPE` it seems that for some reason, by default we escape unicode characters which isn't needed in JSON an just inflates the size. The `NOESCAPE` option made the code behave saner and stopped escaping unicode chars. And there's a mention in the docs that this **should** be the default behaviour and will be in the future. So I'm going to break compatibility and just remove this option.

Last point regarding `NOESCAPE` is that it also stopped escaping control characters (ascii value < 32) which can create invalid JSON output. ([see RFC section 7](https://tools.ietf.org/rfc/rfc8259.txt)). So the original implementation was buggy anyway.
