### ISSUE TITLE
Set correct version in code instead of hardcoded "99.99.99"

### ISSUE THREAD

**Issue by gavrie** [RedisJSON/RedisJSON#162]
The current code uses hardcoded version `99.99.99`. We should do something like in the v1 code where it's built from something like `version.h`.

**Comment by jrtaisto** [comment]
It has been over a year since this was opened. Is there a procedure for doing the build against a tagged version and having that version show up when you do the module list?  I can understand having the 99.99.99 for the head if it's untagged, but if you checkout a tagged version and build, it would be nice for that to show in module list.

**Comment by gkorland** [comment]
Now that 2.0.0 for officially released the 2.0.0 branch and tags hold specific versions.
