### ISSUE TITLE
Catch FLUSHALL/FLUSHDB event on Redis 6

### ISSUE THREAD

**Issue by gkorland** [RedisJSON/RedisJSON#180]
Drop index schema?

**Comment by yoav-steinberg** [comment]
Note that I don't think FLUSHDB should drop the index schema only FLUSHALL. FLUSALL is used internally in redis to reset the state before synchronizing with a master or in other cases, so in these cases we also need to clear the shcema. FLUSHDB only resets part of the keyspace so it's not directly related and shouldn't trigger clearing the schema. @gkorland Do you agree?

**Comment by gkorland** [comment]
I think we should  first need to extend the `JSON.INDEX CREATE` to be DB id aware and then FLUSHDB should flush only the relevant indexes

**Comment by yoav-steinberg** [comment]
I verified that ReJSON is broken when working with multi DB's. Fixing this is tricky because when loading/saving values from/to the RDB we don't know how to associate them to a specific DB. This means that when we add loaded values to an index we don't know on what DB that index is. This can be handled in the following ways:
1. Extending the module API similar to `RedisModule_GetKeyNameFromIO` to have something like `RedisModule_GetDbFromIO`
1. Adding some scanning/post processing when RDB load completes.
1. Store the Db name in the values (like already store the key names in the values(!!!))

*Note*: in the current implementation we store the key names inside the values (!!!) in order to handle adding them to the index on loading. This is inefficient and might be bug prone. It can probably be avoided using `RedisModule_GetKeyNameFromIO`. There's a similar issue when calling the `free` callback to free JSON values. We need to know the key name. @oranagra recommends adding the db/key name to the free API callback too.

**Comment by oranagra** [comment]
adding the key name to the `free` callback is a challenge (to make it backwards compatible), but i've seen other requests for that in the past, so i suppose we need to do that some day.

for the record, the current approach of saving the key names inside the value, is obviously broken if someone uses RENAME or DUMP one key, and RESTORE the payload into another.
saving the database id will be broken by MOVE.

**Comment by gkorland** [comment]
@oranagra 
>adding the key name to the free callback is a challenge (to make it backwards compatible), but i've seen other requests for that in the past, so i suppose we need to do that some day.

That will be great if you can add it to the modules API.

>for the record, the current approach of saving the key names inside the value, is obviously broken if someone uses RENAME or DUMP one key, and RESTORE the payload into another. saving the database id will be broken by MOVE.

We known but we didn't have another solution

**Comment by gkorland** [comment]
Please notice RedisJSON 2.0 final version dropped the support for JSON.INDEX and JSON.QGET.
To read more about how to index JSONs using RediSearch see: https://oss.redis.com/redisearch/Indexing_JSON/
