### ISSUE TITLE
MacOS cannot load module

### ISSUE THREAD

**Issue by qxqxq** [RedisJSON/RedisJSON#582]
RedisJSON v2.0.6
1.https://www.rust-lang.org/tools/install
2.cargo build --release
Compiling libc v0.2.109
   Compiling autocfg v1.0.1
   Compiling proc-macro2 v1.0.33
   Compiling unicode-xid v0.2.2
   Compiling cfg-if v1.0.0
   Compiling memchr v2.4.1
   Compiling syn v1.0.82
   Compiling version_check v0.9.3
   Compiling glob v0.3.0
   Compiling log v0.4.14
   Compiling serde_derive v1.0.130
   Compiling serde v1.0.130
   Compiling ryu v1.0.6
   Compiling regex-syntax v0.6.25
   Compiling minimal-lexical v0.2.1
   Compiling unicode-width v0.1.9
   Compiling getrandom v0.1.16
   Compiling cc v1.0.72
   Compiling strsim v0.8.0
   Compiling serde_json v1.0.72
   Compiling bindgen v0.59.2
   Compiling hashbrown v0.11.2
   Compiling ansi_term v0.12.1
   Compiling humantime v2.1.0
   Compiling vec_map v0.8.2
   Compiling bitflags v1.3.2
   Compiling either v1.6.1
   Compiling termcolor v1.1.2
   Compiling itoa v0.4.8
   Compiling unicode-xid v0.0.4
   Compiling peeking_take_while v0.1.2
   Compiling shlex v1.1.0
   Compiling lazycell v1.3.0
   Compiling rustversion v1.0.6
   Compiling lazy_static v1.4.0
   Compiling rustc-hash v1.1.0
   Compiling gimli v0.26.1
   Compiling adler v1.0.2
   Compiling ppv-lite86 v0.2.15
   Compiling quote v0.3.15
   Compiling unicode-segmentation v1.8.0
   Compiling rustc-demangle v0.1.21
   Compiling byteorder v1.4.3
   Compiling array_tool v1.0.3
   Compiling hex v0.3.2
   Compiling redisjson v99.99.99 (/usr/local/Cellar/redis/5.0.6/rejson)
   Compiling linked-hash-map v0.5.4
   Compiling md5 v0.6.1
   Compiling libloading v0.7.2
   Compiling nom v7.1.0
   Compiling num-traits v0.2.14
   Compiling indexmap v1.7.0
   Compiling num-integer v0.1.44
   Compiling miniz_oxide v0.4.4
   Compiling textwrap v0.11.0
   Compiling clang-sys v1.3.0
   Compiling synom v0.11.3
   Compiling heck v0.3.3
   Compiling backtrace v0.3.63
   Compiling itertools v0.10.1
   Compiling syn v0.11.11
   Compiling addr2line v0.17.0
   Compiling atty v0.2.14
   Compiling which v4.2.2
   Compiling num_cpus v1.13.0
   Compiling time v0.1.44
   Compiling quote v1.0.10
   Compiling aho-corasick v0.7.18
   Compiling object v0.27.1
   Compiling clap v2.34.0
   Compiling rand_core v0.5.1
   Compiling dashmap v4.0.2
   Compiling regex v1.5.4
   Compiling num-traits v0.1.43
   Compiling rand_chacha v0.2.2
   Compiling cexpr v0.6.0
   Compiling chrono v0.4.19
   Compiling enum-primitive-derive v0.1.2
   Compiling rand v0.7.3
   Compiling env_logger v0.9.0
   Compiling strum_macros v0.23.1
   Compiling redis-module v0.25.0
   Compiling ijson v0.1.3
   Compiling bson v0.14.1
   Compiling jsonpath_lib v0.2.6 (https://github.com/RedisJSON/jsonpath.git?branch=generic_json_path#19804333)
    Finished release [optimized + debuginfo] target(s) in 1m 05s
3.redis-server --loadmodule ./librejson.dylib
error:

5130:M 19 Dec 2021 04:14:19.878 # Server initialized
5130:M 19 Dec 2021 04:14:19.878 * <ReJSON> version: 999999 git sha: 91892dd branch: master
5130:M 19 Dec 2021 04:14:19.878 * <ReJSON> Exported RedisJSON_V1 API
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/qxq/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-module-0.25.0/src/context/mod.rs:286:52
stack backtrace:
   0:        0x10f2b6881 - std::backtrace_rs::backtrace::libunwind::trace::h310ac7aacd577bf8
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x10f2b6881 - std::backtrace_rs::backtrace::trace_unsynchronized::had33a05577c9d011
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10f2b6881 - std::sys_common::backtrace::_print_fmt::hd9acce3818e5f1bc
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10f2b6881 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4edbddd26fc45697
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x10f2cfc7b - core::fmt::write::h266c957f12b1655a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
   5:        0x10f2b4b5a - std::io::Write::write_fmt::h65d4ee621e8d810d
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
   6:        0x10f2b78d5 - std::sys_common::backtrace::_print::h9a5ef67cfa8b031e
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x10f2b78d5 - std::sys_common::backtrace::print::h99dfbbc518768f3b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x10f2b78d5 - std::panicking::default_hook::{{closure}}::h5b4886cd9f93dfca
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
   9:        0x10f2b74bf - std::panicking::default_hook::h986d152c7bd7e732
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
  10:        0x10f2b7fc0 - std::panicking::rust_panic_with_hook::h151f3b3bf37b4f17
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:624:17
  11:        0x10f2b7a34 - std::panicking::begin_panic_handler::{{closure}}::hf6660086d9ebd48c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:519:13
  12:        0x10f2b6cf7 - std::sys_common::backtrace::__rust_end_short_backtrace::h34152178ea368a9a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
  13:        0x10f2b79ca - rust_begin_unwind
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
  14:        0x10f2de80f - core::panicking::panic_fmt::hb64a2db862b4aca0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
  15:        0x10f2de767 - core::panicking::panic::h709f8bbcee9c47c1
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
  16:        0x10f270fd1 - core::option::Option<T>::unwrap::h53ac88c1390417ad
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/option.rs:746:21
  17:        0x10f270fd1 - redis_module::context::Context::set_module_options::h0516aefa467de8ad
                               at /Users/qxq/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-module-0.25.0/src/context/mod.rs:286:18
  18:        0x10f249872 - rejson::intialize::h9d5595191442af28
                               at /usr/local/Cellar/redis/5.0.6/rejson/src/lib.rs:447:13
  19:        0x10f249872 - RedisModule_OnLoad
                               at /Users/qxq/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-module-0.25.0/src/macros.rs:157:20
  20:        0x10f0fb7d9 - _moduleLoad
  21:        0x10f0fb735 - _moduleLoadFromQueue
  22:        0x10f096428 - _main
fatal runtime error: failed to initiate panic, error 5
Abort trap: 6

I need some help, thank you.

**Comment by gkorland** [comment]
Which version of Redis server are you using? Please make sure it's 6.0+

**Comment by qxqxq** [comment]
Oh, sorry my Redis server V =5.0.6, can I only upgrade to 6.0+ to use RedisJSON? Can I download other versions of RedisJSON?

**Comment by qxqxq** [comment]
Oh, sorry my Redis server V =5.0.6, can I only upgrade to 6.0+ to use RedisJSON? Can I download other versions of RedisJSON?

**Comment by qxqxq** [comment]
Oh, sorry my Redis server V =5.0.6, can I only upgrade to 6.0+ to use RedisJSON? Can I download other versions of RedisJSON?

**Comment by gkorland** [comment]
For RedisJSON >2.0 you need redis-server 6.0+.
You can use RedisJSON 1.0.x if you need Redis 5.0.6 support.

**Comment by robben009** [comment]
> For RedisJSON >2.0 you need redis-server 6.0+. You can use RedisJSON 1.0.x if you need Redis 5.0.6 support.

now, I made the same mistake，but my redis is "redis-cli 6.0.8"

[root@hjz RedisJSON-2.0.6]# cargo build --release Compiling libc v0.2.112 Compiling autocfg v1.0.1 Compiling proc-macro2 v1.0.33 Compiling unicode-xid v0.2.2 Compiling memchr v2.4.1 Compiling cfg-if v1.0.0 Compiling syn v1.0.82 Compiling glob v0.3.0 Compiling version_check v0.9.3 Compiling serde_derive v1.0.131 Compiling log v0.4.14 Compiling cc v1.0.72 Compiling serde v1.0.131 Compiling minimal-lexical v0.2.1 Compiling unicode-width v0.1.9 Compiling regex-syntax v0.6.25 Compiling getrandom v0.1.16 Compiling either v1.6.1 Compiling serde_json v1.0.73 Compiling termcolor v1.1.2 Compiling strsim v0.8.0 Compiling bindgen v0.59.2 Compiling humantime v2.1.0 Compiling bitflags v1.3.2 Compiling ansi_term v0.12.1 Compiling hashbrown v0.11.2 Compiling vec_map v0.8.2 Compiling shlex v1.1.0 Compiling itoa v1.0.1 Compiling ryu v1.0.9 Compiling peeking_take_while v0.1.2 Compiling lazycell v1.3.0 Compiling lazy_static v1.4.0 Compiling rustversion v1.0.6 Compiling rustc-hash v1.1.0 Compiling unicode-xid v0.0.4 Compiling ppv-lite86 v0.2.15 Compiling unicode-segmentation v1.8.0 Compiling quote v0.3.15 Compiling adler v1.0.2 Compiling gimli v0.26.1 Compiling rustc-demangle v0.1.21 Compiling hex v0.3.2 Compiling array_tool v1.0.3 Compiling byteorder v1.4.3 Compiling md5 v0.6.1 Compiling linked-hash-map v0.5.4 Compiling redisjson v2.0.6 (/usr/local/redis/RedisJSON-2.0.6) Compiling num-traits v0.2.14 Compiling indexmap v1.7.0 Compiling miniz_oxide v0.4.4 Compiling num-integer v0.1.44 Compiling clang-sys v1.3.0 Compiling nom v7.1.0 Compiling libloading v0.7.2 Compiling backtrace v0.3.63 Compiling textwrap v0.11.0 Compiling synom v0.11.3 Compiling heck v0.3.3 Compiling addr2line v0.17.0 Compiling itertools v0.10.3 Compiling syn v0.11.11 Compiling num_cpus v1.13.0 Compiling time v0.1.44 Compiling atty v0.2.14 Compiling which v4.2.2 Compiling quote v1.0.10 Compiling aho-corasick v0.7.18 Compiling object v0.27.1 Compiling rand_core v0.5.1 Compiling dashmap v4.0.2 Compiling clap v2.34.0 Compiling num-traits v0.1.43 Compiling regex v1.5.4 Compiling cexpr v0.6.0 Compiling rand_chacha v0.2.2 Compiling chrono v0.4.19 Compiling enum-primitive-derive v0.1.2 Compiling strum_macros v0.23.1 Compiling env_logger v0.9.0 Compiling rand v0.7.3 Compiling redis-module v0.25.0 Compiling ijson v0.1.3 Compiling bson v0.14.1 error: failed to run custom build command forredis-module v0.25.0`

Caused by:
process didn't exit successfully: /usr/local/redis/RedisJSON-2.0.6/target/release/build/redis-module-7f5f32dcd205f513/build-script-build (exit status: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/include/" "-Wall" "-Wextra" "-DREDISMODULE_EXPERIMENTAL_API" "-o" "/usr/local/redis/RedisJSON-2.0.6/target/release/build/redis-module-e3a4be5d3b123ac9/out/src/redismodule.o" "-c" "src/redismodule.c"
exit status: 0
AR_x86_64-unknown-linux-gnu = None
AR_x86_64_unknown_linux_gnu = None
HOST_AR = None
AR = None
running: "ar" "cq" "/usr/local/redis/RedisJSON-2.0.6/target/release/build/redis-module-e3a4be5d3b123ac9/out/libredismodule.a" "/usr/local/redis/RedisJSON-2.0.6/target/release/build/redis-module-e3a4be5d3b123ac9/out/src/redismodule.o"
exit status: 0
running: "ar" "s" "/usr/local/redis/RedisJSON-2.0.6/target/release/build/redis-module-e3a4be5d3b123ac9/out/libredismodule.a"
exit status: 0
cargo:rustc-link-lib=static=redismodule
cargo:rustc-link-search=native=/usr/local/redis/RedisJSON-2.0.6/target/release/build/redis-module-e3a4be5d3b123ac9/out

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-.so', 'libclang.so.', 'libclang-.so.'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (invalid: [])"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/lib.rs:2144:31
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
`
