### ISSUE TITLE
Extend the module with json.copy command.

### ISSUE THREAD

**Issue by shatilov-diman** [RedisJSON/RedisJSON#620]
name: json.copy
title: "[Proposal]: extend the RedisJSON module with json.copy command."
labels: enhancement
body:
  I believe it will be very nice to have feature to copy/move some part of json to another place
  Something like that:
 `json.copy <source_key> <destination_key|@> <source_path> <destination_path|@> [nx|xx|mv]`
where @ at destination_key means 'equal to source_key'
and @ at destination_path means 'equal to source_path'

**Comment by gkorland** [comment]
@shatilov-diman thanks for the feature request, I would love to hear more about the use case.
Meanwhile you can easily achieve similar behavior with a Lua script.

Also, please notice multi-keys operations in Redis are limited to same keys that are located in the same slot.

**Comment by shatilov-diman** [comment]
I think it's little complicated to use separate file for just copy/move subtree.
And I absolutely forget that I can calling eval instead of evalsha (because of layers of abstraction :)
Thank you!

I have two separate cases for the feature request:
1. Renaming/restructing the tree while developing new feature or refactoring an old.
2. I would like to have a 'template' json for generation a new instance of an entity with predefined structure.
Thank you!

**Comment by Cajuteq** [comment]
Hi, first I'm interested in the "template" use case :

I have a json storing questions and content (description, link to images, ...) for a workshop 
and would want to create a copy for each people attending the workshop in order to save their responses by adding keys in the json at the right place

I know people will say I don't need to duplicate questions and will propose to work with ids for questions, but the questions doesn't have ids and I don't want to bother creating this extra layer both in the storage and the visualization app. Also the respondent data are short lived and so the data volume is not a problem for me

Also for the "restructuring" use case :
I would want to use the copy function to replace the displayed version of the workshops while storing (copying) the previous in a an archive folder ("workshops_archives:")

**Comment by oshadmi** [comment]
Seems related to https://github.com/RedisJSON/RedisJSON/issues/150
which enables to copy from a path to a path, but in this issue (#620) it can also copy from a different key,
