### ISSUE TITLE
Unexpected behaviour with filters!

### ISSUE THREAD

**Issue by 0xhiro** [RedisJSON/RedisJSON#851]
I have been using Redis Json for months with no trouble, using the docker container. I finally decided to run Redis on my computer without docker. I have it installed and i have the Redis-Json module installed too and working normally, but there is something wrong which i can't understand why it happens. Here it is in only two commands given to the redis-cli:

First command: `JSON.SET places $ '[ {"continent": "europe", "people": [] }, {"continent": "asia", "people": [] }  ]' `

Second command: `JSON.ARRAPPEND places '$.*[?(@.continent=="asia")].people' '{ "name":"john", "age":12 }' `

These two commands work perfectly when run with the redis-json docker  container, but gives this error when run in Redis version 7.0.5 and version 6.0.16, without docker:  `(empty array)` .

**Comment by gkorland** [comment]
Which version of RedisJSON are you using?

**Comment by hirohido** [comment]
I just cloned the repository and compiled it

**Comment by gkorland** [comment]
@TomerHekmati just pointed out that the right query should be:

```
JSON.ARRAPPEND places '$[?(@.continent=="asia")].people' '{ "name":"john", "age":12 }'
```

**Comment by hirohido** [comment]
Okay thanks! I wonder why it works on the docker container though.

**Comment by gkorland** [comment]
We replaced our JSONPath parser with a faster and more robust parser, it seems like the previous parser supported this strange behavior. Thanks for pointing it out, we'll see if we can "re-introduce" this none standard behavior to avoid backward compatibility issues.

**Comment by hirohido** [comment]
What about when i am nesting filters like `$.*[?(@.id=={:?})].players.*[?(@.id=={:?})].state.ammo`
does this translate to `$[?(@.id=={:?})].players.*[?(@.id=={:?})].state.ammo` ??

**Comment by oshadmi** [comment]
@hirohido There is no translation. It is just a question whether the current level is filtered, so each of its elements is checked against the filter,
Or, if there is a `.*` before the filter, then each child is iterated, and then, on each child, each of its elements is checked against the filter (actually a grandchild of the element the filter was applied to)

Regarding keeping the previous behavior, we do not want to maintain it since it is buggy.
For example, consider a doc such as
```
JSON.SET temp $ '[[{"a":[10],"b":100}],{"a":[10],"b":200},{"a":[10],"b":300}]'
```
(1st element is an array, 2nd and 3rd are objects)

We want the 2 options, with and without the `.*`, to behave differently
```
JSON.GET temp '$.*[?(@.a[?(@==10)])]'
"[{\"a\":[10],\"b\":100}]"

JSON.GET temp '$[?(@.a[?(@==10)])]'
"[{\"a\":[10],\"b\":200},{\"a\":[10],\"b\":300}]"

```

**Comment by 0xhiro** [comment]
Okay. Thanks for the response. I"m closing this issue since it has been resolved.
