### ISSUE TITLE
RedisJSON Should elaborate on why there are extraneous array brackets around returned values

### ISSUE THREAD

**Issue by PerMildner** [RedisJSON/RedisJSON#882]
The page `https://redis.io/docs/stack/json/` shows examples of reading JSON values from the database.

However, it is surprising, and not explained, why there seem to be an extraneous array bracket pair around the returned values.

For instance, the first example is:

```
127.0.0.1:6379> JSON.SET animal $ '"dog"'
"OK"
127.0.0.1:6379> JSON.GET animal $
"[\"dog\"]"
127.0.0.1:6379> JSON.TYPE animal $
1) "string"
```

But, since the value associated with animal is a _string_, it is surprising that the returned value looks like (a string representation of) a JSON array containing the value.

(I am completely new to Redis, but presumably that makes me the target audience for this page).

**Comment by oshadmi** [comment]
@PerMildner Thank you for your feedback.
Please mind that a JSONPath may match more than a single value, when using JSONPath operators such as wildcard, recursive descent, etc., and therefore it is required to return a top-level array.
In order to make the reply backward compatible with previous releases, a string is returned.
In order to make the reply format consistent, a JSON string of a top-level array is returned.

Please see [examples](https://redis.io/commands/json.get/#examples) for the [JSON.GET](https://redis.io/commands/json.get/) command

**Comment by oshadmi** [comment]
@nermiller Let's review the documentation of the `JSON.GET` return value and consider mentioning or referencing it also from other pages ( https://redis.io/docs/stack/json/, https://redis.io/docs/stack/json/path/)
